### ISSUE TITLE
Having destinations in a planner

### ISSUE THREAD

**Issue by h-kt** [Adrian-Moreira/PlanPals#62]
As a user, I want to create a planner multiple destinations.

Estimate: 2 days

**Backend**: Create the Destination model, implement logic for handling the creation request, and ensure proper validation @h-kt 

**Frontend**: Set up requests according to the endpoints documented @hridaimehta  , displaying relevant information, while allowing user to edit.

**Comment by hridaimehta** [comment]
- Work has been pushed for destinations. Functionality for add/edit and delete destination button are up
